### ISSUE TITLE
Openssh binaries not set executable permission

### ISSUE THREAD

**Issue by guoxiao** [Linuxbrew/legacy-linuxbrew#541]
1. Install linuxbrew
2. Install openssh by `brew install homebrew/dupes/openssh`
3. The binaries are not set executable bit:

```
% ll .linuxbrew/Cellar/openssh/7.1p1/bin
total 2.1M
-r--r--r-- 1 foobar foobar  67K 9月   6 14:09 scp
-r--r--r-- 1 foobar foobar 111K 9月   6 14:09 sftp
lrwxrwxrwx 1 foobar foobar    5 9月   6 14:09 slogin -> ./ssh
-r--r--r-- 1 foobar foobar 603K 9月   6 14:09 ssh
-r--r--r-- 1 foobar foobar 303K 9月   6 14:09 ssh-add
-r--r--r-- 1 foobar foobar 319K 9月   6 14:09 ssh-agent
-r--r--r-- 1 foobar foobar 359K 9月   6 14:09 ssh-keygen
-r--r--r-- 1 foobar foobar 367K 9月   6 14:09 ssh-keyscan
```

It seems that it only happens in linux, so I open this issue here.

**Comment by sjackman** [comment]
Which Linux distribution are you using?

**Comment by guoxiao** [comment]
CentOS release 6.4

**Comment by guoxiao** [comment]
I just updated my linuxbrew and now brew cannot be run with the following error:

```
/opt/home/guoxiao/.linuxbrew/Library/Homebrew/global.rb:30:in `<top (required)>': uninitialized constant OS_VERSION (NameError)
        from /opt/home/guoxiao/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/home/guoxiao/.linuxbrew/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/home/guoxiao/.linuxbrew/Library/brew.rb:15:in `<main>'
```

**Comment by sjackman** [comment]
Sorry for that. That issue has been resolved. See #648

**Comment by sjackman** [comment]
Does PR #612 fix your original issue?

**Comment by guoxiao** [comment]
No. I test reinstalling `openssh` just now, and the issue still exists.

**Comment by sjackman** [comment]
I'm on vacation in Thailand until the new year. Please bump this thread after then. Sorry for the delay.
